DROP DATABASE IF EXISTS EXAMPLE;

CREATE DATABASE EXAMPLE CHARACTER SET utf8 COLLATE utf8_general_ci;

use EXAMPLE;
SET SQL_SAFE_UPDATES = 0;


CREATE TABLE USERS (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name varchar(200) DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO USERS (id, name) VALUES 
(1, 'Nabby');
